/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  tutorialSidebar: [
    // { type: 'autogenerated', dirName: '.' },
    "intro",
    {
      type: "category",
      label: "Contents and Figures",
      items: [{ type: "autogenerated", dirName: "chap-0" }],
    },
    {
      type: "category",
      label: "1. Introduction",
      items: [{ type: "autogenerated", dirName: "chap-1" }],
    },
    {
      type: "category",
      label: "2. Syntax",
      items: [{ type: "autogenerated", dirName: "chap-2" }],
    },
    {
      type: "category",
      label: "3. Evaluation and Compilation",
      items: [{ type: "autogenerated", dirName: "chap-3" }],
    },
    {
      type: "category",
      label: "4. Types and Classes",
      items: [{ type: "autogenerated", dirName: "chap-4" }],
    },
    {
      type: "category",
      label: "5. Data and Control Flow",
      items: [{ type: "autogenerated", dirName: "chap-5" }],
    },
    {
      type: "category",
      label: "6. Iteration",
      items: [{ type: "autogenerated", dirName: "chap-6" }],
    },
    {
      type: "category",
      label: "7. Objects",
      items: [{ type: "autogenerated", dirName: "chap-7" }],
    },
    {
      type: "category",
      label: "8. Structures",
      items: [{ type: "autogenerated", dirName: "chap-8" }],
    },
    {
      type: "category",
      label: "9. Conditions",
      items: [{ type: "autogenerated", dirName: "chap-9" }],
    },
    {
      type: "category",
      label: "10. Symbols",
      items: [{ type: "autogenerated", dirName: "chap-10" }],
    },
    {
      type: "category",
      label: "11. Packages",
      items: [{ type: "autogenerated", dirName: "chap-11" }],
    },
    {
      type: "category",
      label: "12. Numbers",
      items: [{ type: "autogenerated", dirName: "chap-12" }],
    },
    {
      type: "category",
      label: "13. Characters",
      items: [{ type: "autogenerated", dirName: "chap-13" }],
    },
    {
      type: "category",
      label: "14. Conses",
      items: [{ type: "autogenerated", dirName: "chap-14" }],
    },
    {
      type: "category",
      label: "15. Arrays",
      items: [{ type: "autogenerated", dirName: "chap-15" }],
    },
    {
      type: "category",
      label: "16. Strings",
      items: [{ type: "autogenerated", dirName: "chap-16" }],
    },
    {
      type: "category",
      label: "17. Sequences",
      items: [{ type: "autogenerated", dirName: "chap-17" }],
    },
    {
      type: "category",
      label: "18. Hash Tables",
      items: [{ type: "autogenerated", dirName: "chap-18" }],
    },
    {
      type: "category",
      label: "19. Filenames",
      items: [{ type: "autogenerated", dirName: "chap-19" }],
    },
    {
      type: "category",
      label: "20. Files",
      items: [{ type: "autogenerated", dirName: "chap-20" }],
    },
    {
      type: "category",
      label: "21. Streams",
      items: [{ type: "autogenerated", dirName: "chap-21" }],
    },
    {
      type: "category",
      label: "22. Printer",
      items: [{ type: "autogenerated", dirName: "chap-22" }],
    },
    {
      type: "category",
      label: "23. Reader",
      items: [{ type: "autogenerated", dirName: "chap-23" }],
    },
    {
      type: "category",
      label: "24. System Construction",
      items: [{ type: "autogenerated", dirName: "chap-24" }],
    },
    {
      type: "category",
      label: "25. External Environment",
      items: [{ type: "autogenerated", dirName: "chap-25" }],
    },
    // { type: "category", label: "26. Environments", items: ["environments/index"] },
    {
      type: "category",
      label: "26. Environments",
      items: [
        "environments/index",
        {
          type: "category", label: "Environments Dictionary",
          link: {
            type: 'generated-index',
            title: 'Environments Dictionary',
          },
          items: [
            "chap-7/h-h-dictionary/find-class_accessor",
            "chap-5/f-d-dictionary/fdefinition_accessor",
            "chap-10/ba-c-dictionary/symbol-value_accessor",
            "chap-4/e-e-dictionary/deftype_macro",
            "chap-3/d-i-dictionary/defmacro_macro",
            "chap-5/f-d-dictionary/defun_macro",
            "chap-7/h-h-dictionary/defgeneric_macro",
            "chap-7/h-h-dictionary/define-method-combination_macro",
            "chap-5/f-d-dictionary/defparameter_defvar_macro",
            "chap-7/h-h-dictionary/defclass_macro",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "27. Meta Object Protocol",
      items: [{ type: "autogenerated", dirName: "meta-object-protocol" }],
    },
    "dictionary-entries",
    {
      type: "category",
      label: "Glossary",
      items: [{ type: "autogenerated", dirName: "chap-26" }],
    },
  ],
  // contributeSidebar: [{type: 'autogenerated', dirName: 'contribute'}],
  // whyLispSidebar: [{type: 'autogenerated', dirName: 'whylisp'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      // items: [['tutorial-basics/create-a-docume]nt', label: "docume]nt"],
    },
  ],
   */
};

export default sidebars;
